[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings= ["@chainlink=lib/chainlink"]
fs_permissions = [{ access = "read", path = "/home/io10-0x/foundryprojects/foundryfundme/broadcast", allow = ["*"] }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
